### PR TITLE
Add NetBeans build guide

### PR DESCRIPTION
**Pull request by geight**
Closes https://github.com/momentum-mod/docs/issues/64; relates to https://github.com/momentum-mod/game/pull/894 (mentioned in the `docs` issue)

Adds a new guide post with the steps outlined in the NetBeans build PR

### CODE REVIEW

**Comment by braem** [comment]
Crap, that issue should've been closed months ago since we're closed source now. I believe we should move these build guides to the game repo @Gocnak , and keep this site removed from 0.8.7 as it already is with the new, removed, and modified cvars.

**Comment by geight** [comment]
I'll wait for confirmation, but in that case I can easily just put this in a `docs/` directory and make it a more GitHub-friendly Markdown file. 👍

**Comment by Gocnak** [comment]
Yep let's move em over to game/

**Comment by geight** [comment]
Closing in favor of moving this to a `docs/` directory in https://github.com/momentum-mod/game.

**Pull request closed without merging**
