### PR TITLE
add mat_error_texture convars

### LINKED ISSUE #187: Add mat_error_texture_type and mat_error_texture_replace page
We added `mat_error_texture_type` and `mat_error_texture_replace` and they dont have doc pages explaining how they work or what the values do.

### PR DESCRIPTION
**Pull request by patrickmoc**
closes #187 

Added convar pages for mat_error_texture_type and mat_error_texture_replace.

### CODE REVIEW

**Review by Gocnak — CHANGES_REQUESTED** [review]
Can we get some images of the texture replacement?

**Comment by patrickmoc** [comment]
oh I misread that and added images to the type page

**Comment by Gocnak** [comment]
Both are fine!

> 
> 
> oh I misread that and added images to the type page

**Review by Gocnak — CHANGES_REQUESTED** [review]
The type images should be in-game, like the utopia_replace image shows, one with the normal purple+black, and another with the very nice looking replacement, showing the effectiveness of it.

**Review by Gocnak — APPROVED** [review]

**Pull request merged**
