### PR TITLE
Added stdshader removal or rename

### PR DESCRIPTION
**Pull request by tuckerthomas**
Was going through the build process and stumbled upon a hiccup, searched discord and found many references to this solution and recommendations for the build guide.

So, I figured I would try to include it. Let me know if there's anything else that's needed.

### CODE REVIEW

**Comment by patrickmoc** [comment]
As far as I'm aware this is only an issue for people trying to build without a key because of the momentumdev folder hosted online? I'm not certain whether this belongs as a step for the build guide if most contributors wouldn't need to deal with it ever. Not completely familiar with this issue but it might be a case where it's better to fix the hosted files instead of cluttering the build guide with workarounds. Requesting input from @Gocnak

**Comment by tuckerthomas** [comment]
Fair enough, my only concern was that people without keys, who have not contributed to the code wouldn't be able to build without having to lookup the issue. Or could the dlls be removed from the drive zip?

**Comment by Gocnak** [comment]
Should be fixed by #65 , can you confirm?

**Comment by Gocnak** [comment]
Can be re-opened if #65 did not fix this.

**Pull request closed without merging**
