### PR TITLE
Update/Add some Header images to Entity pages

### PR DESCRIPTION
**Pull request by McGravel**
Related to #113 

Adds a few consistent header images to some pages which have their own tool textures, also replaces and reduces the size of a few existing ones, such as Slide and Teleport.

Example:

### CODE REVIEW

**Comment by braem** [comment]
These look great! Much better :)

Might be a good idea to reference the related tool texture (as in path) at the bottom in the respective docs. Something like "This entity has a related tool texture located in 'tool/path', which eases readability in hammer's 3D view. This can still be textured the normal tool texture if desired."
Not the greatest wording there but you get the idea.

**Comment by McGravel** [comment]
Sounds like a good idea - might add them as a small caption below the header perhaps?

**Comment by McGravel** [comment]
My initial idea of that caption:

Unsure about it atm, could reword or use some different formatting option?

**Comment by braem** [comment]
Actually, since this will be copied for multiple pages, it might be best as a metadata field and have it laid out in `single.html`. Similar to how the safeguards are done (see https://github.com/momentum-mod/docs/pull/54).

If you aren't comfortable with that no worries I will be able to do it. The formatting on that kind of stuff (related safeguards, cmd params, cvar bounds, etc) is a bit gross anyways should be touched up to look like what youve done here.

**Pull request merged**
