### PR TITLE
Update Momentum Favicon

### PR DESCRIPTION
**Pull request by patrickmoc**
### Fix
The favicon was missed in #51 so it displays the outdated momentum logo, replaced with the new transparent icon,

### Screenshots

Current favicon:
image

Proposed favicon:
image

### CODE REVIEW

**Comment by Gocnak** [comment]
What Brae mentions is true, you can use the .ico file from the game's momentum/resource/ folder.

**Comment by patrickmoc** [comment]
the icon file was added in the first commit, and is not really needed, I have removed it and left in only the png modification.

**Comment by Gocnak** [comment]
Was this tested across chrome and Firefox? I'm not sure if all browsers support just png favicons, but if it's tested and is fine then I'm good with this.

**Comment by patrickmoc** [comment]
image
this is the icon working in firefox. The old version of the favicon was indeed just a png so it should behave the same on most browsers as it did before.

**Pull request merged**
