### PR TITLE
Create docs issue fourms

### LINKED ISSUE #268: Issue templates
The website repo has issue templates this repo should too, and most if not all of them can be copied over

### PR DESCRIPTION
**Pull request by tmob03**
Resolves #268

### CODE REVIEW

**Comment by AWildErin** [comment]
I don't think we need feature and bug issue templates here do we? Seems a bit weird imo to have them on the docs repo

**Comment by tmob03** [comment]
Idk, the issue said most or all, so I took out the one's the definitely aren't needed for the docs website, these two felt a bit unneeded but I thought maybe they might have a use

**Comment by AWildErin** [comment]
Would be worth somebody else chiming in with their opinion from Momentum, but I don't feel they're really required in the docs repo personally

**Comment by hexaflexahexagon** [comment]
Could maybe update them to "new / update / deletion" or something

**Comment by tmob03** [comment]
Oh that's a good idea i'll do that

**Comment by tmob03** [comment]
Alright I did that, three new labels to add: "creation", "deletion", and "update" in place of the standard "documentation" label.

**Review by braem — CHANGES_REQUESTED** [review]
Quite often we'll have issues revolving around a specific area (internal merge request) which adds, changes, and removes documentation all at once (movement refactor was a good example). So I think we should consolidate all those into 1 form of 'Documentation'.

We do however need feature and bug submissions for the website itself. Eg. Adding the ability to display default/min/max values from metadata was a feature, and fixing broken links was a bug. Neither of those related were actual documentation.

**Comment by hexaflexahexagon** [comment]
Good points by brae. Looking at the existing issue labels we have now I'd suggest something like:

- [ ] Documentation (including OPTIONAL sections for add/edit/remove so you can have one, multiple, or all populated with info)
- [ ] Technical Guide (used for like shaders and mapping guides for new features)
- [ ] Gamemode Guide (maybe? we have a tag for this but IDK how frequently these types of things would actually come up. all the gamemode guides are stubbed right now so it'd just be for modification suggestions)
- [ ] Website (meta changes that don't change documentation themselves but rather the website's config or styling or something
- [ ] Miscellaneous (maybe, because some platforms still won't let you add blank issues without using a template)

**Pull request closed without merging**
